add control func and modify some details

diff --git a/lib/functions b/lib/functions
--- a/lib/functions
+++ b/lib/functions
@@ -34,6 +34,11 @@ insert() {
 
 # initialize the directories
 initDir() {
+    if [ $streamOrigin = xml ]; then
+        if [ ! -d $streamPath ]; then
+            mkdir -p $streamPath
+        fi
+    fi
     if [ ! -d $logPath ]; then
         mkdir -p $logPath
     fi
@@ -47,17 +52,49 @@ rmDir() {
     if [ -d $tmpPath ]; then
         rm -rf $tmpPath
     fi
+    if [ -d $streamPath ]; then
+        rm -rf $streamPath
+    fi
+}
+
+# parse xml node to stream files whose name is name node and content is source node 
+xml2streams() {
+    pythonCmd=`which python`
+    if [ $? -ne 0 ]; then
+        echo -e "[\033[1;31mERROR:\033[0m] python is not installed"
+        return 1
+    fi
+    if [ ! -f $xmlPath ]; then
+        echo -e "[\033[1;31mERROR:\033[0m] xml file doesn't exist in $xmlPath"
+        return 1
+    fi
+    $pythonCmd $libPath/xmlParser.py $xmlPath $streamPath
+    if [ $? -ne 0 ]; then
+        echo -e "[\033[1;31mERROR:\033[0m] xmlFile to stream files failed"
+        return 1
+    fi
+    return 0
 }
 
 # start iptvagent
 startAgent(){
-    REDISSERVER=`which redis-server`
-    if [ $? -ne 0 ]; then
-        echo -e "[\033[1;31mERROR:\033[0m] redis is not installed"
-        return 1
-    fi
-    $REDISSERVER > /dev/null &
     initDir
+    if [ $streamOrigin = xml ]; then
+        xml2streams
+        if [ $? -ne 0 ]; then
+            rmDir
+            return 1
+        fi
+    elif [ $streamOrigin = db ]; then
+        if [ $cached = on ]; then
+            REDISSERVER=`which redis-server`
+            if [ $? -ne 0 ]; then
+                echo -e "[\033[1;31mERROR:\033[0m] redis is not installed"
+                return 1
+            fi
+            $REDISSERVER > /dev/null 2>&1 &
+        fi
+    fi
     cp $crondPath/iptvagent /etc/cron.d/
     $daemonPath/iptvagentd &
     echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] iptvagent start manually" >> $logPath/iptvagent.log
@@ -67,6 +104,7 @@ startAgent(){
 # stop iptvagent
 stopAgent(){
     ps -ef|grep iptvagentd|grep -v grep|awk '{print $2}'|xargs kill -9
+    ps -ef|grep server.py|grep -v grep|awk '{print $2}'|xargs kill -9
     if [ -f /etc/cron.d/iptvagent ]; then
         rm /etc/cron.d/iptvagent
     fi
